stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
      - data/raw/yellow_tripdata_2016-01.csv
      - data/raw/yellow_tripdata_2016-02.csv
      - data/raw/yellow_tripdata_2016-03.csv
  feature_extraction:
    cmd: python src/features/extract_features.py
    deps:
      - src/features/extract_features.py
      - data/interim/cleaned_data.csv
    params:
      - extract_features.minibatchkmeans.n_clusters
      - extract_features.minibatchkmeans.n_init
      - extract_features.minibatchkmeans.random_state
      - extract_features.ewm.alpha
    outs:
      - models/scaler.joblib
      - models/kmeans.joblib
      - data/processed/features.csv
  features_processing:
    cmd: python src/features/feature_processing.py
    deps:
      - src/features/feature_processing.py
      - data/processed/features.csv
    outs:
      - data/processed/train_data.csv
      - data/processed/test_data.csv
  training_phase:
    cmd: python src/models/train.py
    deps:
      - src/models/train.py
      - data/processed/train_data.csv
    outs:
      - models/transformer.joblib
      - models/model.joblib
  evaluation_phase:
    cmd: python src/models/evaluation.py
    deps:
      - src/models/evaluation.py
      - data/processed/train_data.csv
      - data/processed/test_data.csv
      - models/transformer.joblib
      - models/model.joblib
    outs:
      - run_information.json
  register_model:
    cmd: python src/models/register_model.py
    deps:
      - src/models/register_model.py
      - run_information.json
