name: CI-CD

on: push

jobs:
  Model-Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"
          cache: "pip"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-cicd.txt

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID}}
          aws-region: eu-north-1

      - name: DVC PULL
        run: |
          dvc pull

      - name: Test Model Registry
        env:
          DAGSHUB_USER_TOKEN: ${{secrets.DAGSHUB_TOKEN}}
        run: |
          pytest test/test_model_registry.py

      - name: Test Model Performance
        if: success()
        env:
          DAGSHUB_USER_TOKEN: ${{secrets.DAGSHUB_TOKEN}}
        run: |
          pytest test/test_model_performance.py

      - name: Promote Model
        if: success()
        env:
          DAGSHUB_USER_TOKEN: ${{secrets.DAGSHUB_TOKEN}}
        run: |
          python promote_model.py

      - name: Connect Docker Client to Elastic Container Registry
        run: |
          aws ecr get-login-password --region eu-north-1 | \
          docker login --username AWS --password-stdin 835952944694.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build Docker Image
        if: success()
        run: |
          docker build -t uber-demand:latest .

      - name: Push Image to AWS Elastic Container Registry
        if: success()
        run: |
          docker tag uber-demand:latest 835952944694.dkr.ecr.eu-north-1.amazonaws.com/uber-demand:latest
          docker push 835952944694.dkr.ecr.eu-north-1.amazonaws.com/uber-demand:latest
